sudo: required
dist: trusty
language: cpp
services: docker

env:
    - BUILDTYPE=Default

before_install:
    - sudo docker pull tinytangent/ucore_build_environment
    - sudo docker create --name=ucore_build_environment -it tinytangent/ucore_build_environment
    - sudo apt-get update -qq

install:
    - ls

script:
    - docker cp ucore ucore_build_environment:/
    - docker start ucore_build_environment
    - docker exec ucore_build_environment apt-get install -y ncurses-dev u-boot-tools
    - docker exec ucore_build_environment bash -c "cd /ucore && python misc/evaluate_build.py /opt/ucore_build_environment"

compiler:
    - gcc
