sudo: required
dist: trusty
language: cpp
services: docker

env:
    - GCC_VER=7 UCORE_ARCH=i386 UCORE_BOARD=default
    - GCC_VER=7 UCORE_ARCH=amd64 UCORE_BOARD=default
    - GCC_VER=7 UCORE_ARCH=arm UCORE_BOARD=goldfishv7
    - GCC_VER=7 UCORE_ARCH=arm UCORE_BOARD=pandaboardes
    - GCC_VER=7 UCORE_ARCH=arm UCORE_BOARD=raspberrypi
    - GCC_VER=7 UCORE_ARCH=arm UCORE_BOARD=zedboard


before_install:
    - sudo docker pull tinytangent/ucore_build_environment:gcc7
    - sudo docker create --name=ucore_build_environment -it tinytangent/ucore_build_environment:gcc7
    - sudo apt-get update -qq

install:
    - ls

script:
    - docker cp ucore ucore_build_environment:/
    - docker start ucore_build_environment
    - docker exec ucore_build_environment apt-get install -y ncurses-dev u-boot-tools
    - |
      docker exec ucore_build_environment bash -c "cd /ucore && python misc/evaluate_build.py \
      --gcc_major_versions=${GCC_VER} --ucore_arch=${UCORE_ARCH} --ucore_board=${UCORE_BOARD} \
      /opt/ucore_build_environment"

compiler:
    - gcc
